### ISSUE TITLE
Models are not loading

### ISSUE THREAD

**Issue by ioskevinshah** [Norod/CoreML-StyleTransfer#1]
Hello,

Thanks for sharing the style transfer CoreML models.

But they are not opening.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/45232432/170863519-d360dc50-6a32-44b2-9a69-a16958634b35.png">

Also, Can you please add file how to create it.

**Comment by Norod** [comment]
@ioskevinshah Please make sure you have the actual mlmodel files and not just the git lfs reference pointers to the actual model files

**Comment by ioskevinshah** [comment]
Where I can get mlmodel file, I just clone your repo. Please do check below image.

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/45232432/170864261-a2fafffd-6b79-45f7-832c-2122cfccdf64.png">

**Comment by Norod** [comment]
@ioskevinshah From the screenshot you provided there is no way to tell if these are just LFS reference links and not the actual files, I assume that these are only links because otherwise they would have opened. So again, please make sure to have LFS enabled when you checkout the repo and make sure the mlmodel files are not just reference links. Thank you.

**Comment by ioskevinshah** [comment]
Thanks, did you use CreateML or Turicreate?

**Comment by Norod** [comment]
@ioskevinshah Happy you manage to solve the LFS issue. The models in this Repo were all trained with CreateML. The model (1 model with multiple styles) in this old example (haven't checked if it is still working because it's so old) https://github.com/Norod/MLStyleTransferPlayground was trained with Turicreate
